[package]
name = "lauda"
version = "0.1.0"
authors = ["Ceyhun Kerti <ceyhun.kerti@bluecolor.io>"]

[dependencies]
oracle = { version = "0.1", features = ["chrono"] }
config = "0.9"
serde_derive = "^1.0.8"
serde = "^1.0.8"
log = "0.4"
env_logger = "*"